In [1]:
import pandas as pd
import numpy as np

# Max Voting

In [2]:
data = pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [4]:
X = data.iloc[:,:8]
y = data.iloc[:,8:]

In [5]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
ss = StandardScaler()
mm = MinMaxScaler()

In [6]:
X2 = ss.fit_transform(X)

In [7]:
X2 = pd.DataFrame(X2)
X2.columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin','BMI', 'DiabetesPedigreeFunction', 'Age']

In [8]:
X2.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.639947  0.848324       0.149641       0.907270 -0.692891  0.204013   
1    -0.844885 -1.123396      -0.160546       0.530902 -0.692891 -0.684422   
2     1.233880  1.943724      -0.263941      -1.288212 -0.692891 -1.103255   
3    -0.844885 -0.998208      -0.160546       0.154533  0.123302 -0.494043   
4    -1.141852  0.504055      -1.504687       0.907270  0.765836  1.409746   

   DiabetesPedigreeFunction       Age  
0                  0.468492  1.425995  
1                 -0.365061 -0.190672  
2                  0.604397 -0.105584  
3                 -0.920763 -1.041549  
4                  5.484909 -0.020496

In [9]:
X1 = mm.fit_transform(X)

In [10]:
X1 = pd.DataFrame(X1)
X1.columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin','BMI', 'DiabetesPedigreeFunction', 'Age']

In [11]:
X1.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.352941  0.743719       0.590164       0.353535  0.000000  0.500745   
1     0.058824  0.427136       0.540984       0.292929  0.000000  0.396423   
2     0.470588  0.919598       0.524590       0.000000  0.000000  0.347243   
3     0.058824  0.447236       0.540984       0.232323  0.111111  0.418778   
4     0.000000  0.688442       0.327869       0.353535  0.198582  0.642325   

   DiabetesPedigreeFunction       Age  
0                  0.234415  0.483333  
1                  0.116567  0.166667  
2                  0.253629  0.183333  
3                  0.038002  0.000000  
4                  0.943638  0.200000

In [12]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y = train_test_split(X1,y, random_state = 101, stratify=y)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [14]:
model1 = LogisticRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10]

C:\Users\VigneshSS\Anaconda3\envs\new_env\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(array([1, 1, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64), 0.7447916666666666)

In [15]:
model1.score(valid_x, valid_y)

0.7447916666666666

In [16]:
model2 = KNeighborsClassifier(n_neighbors=5)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10]

C:\Users\VigneshSS\Anaconda3\envs\new_env\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


array([1, 1, 1, 0, 1, 0, 0, 0, 0, 1], dtype=int64)

In [17]:
model2.score(valid_x, valid_y)

0.71875

In [18]:
model3 = DecisionTreeClassifier(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10]

array([1, 0, 0, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [19]:
model3.score(valid_x, valid_y)

0.7239583333333334

In [21]:
from statistics import mode
final_pred = np.array([])
for i in range(0,len(valid_x)):
    final_pred = np.append(final_pred, mode([pred1[i], pred2[i], pred3[i]]))

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
accuracy_score(valid_y, final_pred)

0.7552083333333334

In [24]:
accuracy_score(valid_y, pred1), accuracy_score(valid_y, pred2), accuracy_score(valid_y, pred3)

(0.7447916666666666, 0.71875, 0.7239583333333334)

# Averaging

In [27]:
data1 =pd.read_csv('train_cleaned.csv')

In [28]:
#seperating independent and dependent variables
x = data1.drop(['Item_Outlet_Sales'], axis=1)
y = data1['Item_Outlet_Sales']

In [29]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y = train_test_split(x,y, random_state = 101, shuffle=False)

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [31]:
model1 = LinearRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10], model1.score(valid_x, valid_y)

(array([ 2443.32513354,  2788.36657095,  2169.73477778,  2385.33394477,
         2716.58813899,  3771.41850023,  5119.35227101,  4133.40997069,
        -1010.95412123,  1365.9929378 ]),
 0.5551582433748833)

In [32]:
model2 = KNeighborsRegressor(n_neighbors=9)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10], model2.score(valid_x, valid_y)

(array([1859.06155556, 2519.09128889, 2620.88471111, 2277.33191111,
        3801.12617778, 4099.10866667, 5151.88642222, 5378.62831111,
         476.7128    , 1501.15706667]),
 0.5007936087911619)

In [33]:
model3 = DecisionTreeRegressor(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10], model3.score(valid_x, valid_y)

(array([2413.81776312, 2822.71913115,  585.22631071, 2348.86112052,
        3153.22486811, 3544.38935413, 5815.65707727, 5048.681504  ,
         105.25188333, 1595.93215694]),
 0.5735385499094092)

In [34]:
from statistics import mean
final_pred = np.array([])
for i in range(0,len(valid_x)):
    final_pred = np.append(final_pred, mean([pred1[i], pred2[i], pred3[i]]))

In [35]:
from sklearn.metrics import r2_score

In [36]:
r2_score(valid_y, final_pred)

0.5761405825943703

In [37]:
r2_score(valid_y, pred1), r2_score(valid_y, pred2), r2_score(valid_y, pred3)

(0.5551582433748833, 0.5007936087911619, 0.5735385499094092)

## Weighted Averaging

In [38]:
from statistics import mean
final_pred = np.array([])
for i in range(0,len(valid_x)):
    final_pred = np.append(final_pred, mean([pred1[i], pred1[i], pred2[i], pred3[i], pred3[i]]))

In [39]:
r2_score(valid_y, final_pred)

0.5810607676048198

In [40]:
r2_score(valid_y, pred1), r2_score(valid_y, pred2), r2_score(valid_y, pred3)

(0.5551582433748833, 0.5007936087911619, 0.5735385499094092)